language: go
sudo: false
go:
  - "1.12"
  - "1.13"

env:
  - GO111MODULE=on NODE_VERSION=10

before_install:
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
install:
  - nvm install $NODE_VERSION

script:
  - make ensure
  - make test
